/**
 * Shared domain types for the portfolio.
 * Content-driven types (blog posts, project case studies) are generated by
 * Nuxt Content from `content.config.ts`; these describe the hand-authored
 * data in `app/data/*`.
 */

export interface SocialLink {
  label: string
  /** Lucide icon name, e.g. `lucide:github` */
  icon: string
  href: string
  handle?: string
}

export interface NavItem {
  label: string
  to: string
  /** Section id used for scroll-spy on the landing page */
  section?: string
}

export interface ProfileStat {
  /** i18n key stem under `profile.stats.*` — resolves `<key>Label` and `<key>Hint`. */
  key: 'projects' | 'tech' | 'years' | 'focus'
  /** The figure itself (kept out of i18n — numerals / tech names don't translate). */
  value: string
}

export interface SkillCategory {
  /** i18n key stem under `skills.*` — resolves `<id>.title` and `<id>.description`. */
  id: 'frontend' | 'backend' | 'database' | 'tools'
  icon: string
  skills: Skill[]
}

export interface Skill {
  /** Proper noun — not translated. */
  name: string
  /** Lucide (or iconify) icon name */
  icon: string
}

export type ExperienceKind = 'work' | 'education' | 'project'

export interface ExperienceItem {
  kind: ExperienceKind
  period: string
  title: string
  organization: string
  location?: string
  description: string
  technologies: string[]
  current?: boolean
}

export interface Service {
  /** i18n key stem under `services.*` — resolves `<id>.title`, `<id>.description`, `<id>.d1..d4`. */
  id: 'webApps' | 'fullStack' | 'dashboards' | 'apis'
  icon: string
}

/**
 * Non-translatable profile data. All display copy (role, tagline, bio,
 * philosophy, focus list, learning journey, location, availability) lives in
 * `i18n/locales/*.json` under the `profile.*` namespace.
 */
export interface Profile {
  name: string
  displayName: string
  email: string
  resumeUrl?: string
  avatar: string
  /** Number of bio paragraphs authored in i18n as `profile.bio.1..n`. */
  bioCount: number
  /** Number of "current focus" bullets authored in i18n as `profile.focus.1..n`. */
  focusCount: number
  stats: ProfileStat[]
}

/**
 * Shape of a blog post coming out of Nuxt Content (`content/blog/*.md`).
 * Mirrors the zod schema in `content.config.ts` plus Content's own `path`.
 */
export interface BlogPost {
  path: string
  title: string
  description: string
  date: string
  author: string
  category: string
  tags: string[]
  cover?: string
  draft: boolean
  /** Estimated reading time in minutes, derived at render time. */
  readingTime?: number
}

/** A featured project surfaced on the landing page + /projects grid. */
export interface Project {
  slug: string
  title: string
  description: string
  year: number
  role: string
  stack: string[]
  features: string[]
  cover: string
  repo?: string
  demo?: string
  featured: boolean
  /** When true a full Markdown case study exists at content/projects/<slug>.md */
  caseStudy: boolean
}
